name: Build and Deploy

# Run the deployment only when code is committed to teh branch.
on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npm install && grunt release-no-clean

    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: astra/*
        remote_path: ${{ secrets.SSH_PATH_DEVELOPMENT }}
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: Cleanup
      run: rm -rf astra/
