name: Build and Deploy

# Run the deployment only when code is committed to teh branch.
on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Build
      run: npm install && grunt release-no-clean

    - name: Rsync Deployment
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: astra/*
        remote_path: ${{ secrets.SSH_PATH_DEVELOPMENT }}
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: Cleanup
      run: rm -rf astra/
